name: Update submodules

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  update:
    name: 'Submodules update'
    runs-on: ubuntu-latest
    
    # Use the Bash shell regardless whether the Github Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        
    steps:
    # Checkout the repository to the Github Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Pull & update submodules recursively
      run: |
        git submodules update --init --recursive
        git submodules update --recursive --remote
        
    - name: Commit & push changes
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git commit -am "Update submodules"
        git push
